version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      - postgres
    restart: always

  server:
    build: ./server
    ports:
      - "5001:5001"
    container_name: server
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "FitNotesWeb"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always